-- MySQL Script generated by MySQL Workbench
-- Tue Jun 29 17:37:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `baza` ;

-- -----------------------------------------------------
-- Table `baza`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`person` ;

CREATE TABLE IF NOT EXISTS `baza`.`person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `pass` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `cv` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baza`.`Mesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Mesto` ;

CREATE TABLE IF NOT EXISTS `baza`.`Mesto` (
  `idMesto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Mesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`firma` ;

CREATE TABLE IF NOT EXISTS `baza`.`firma` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `idMesto` INT UNSIGNED NOT NULL,
  `opis` VARCHAR(512) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `mesto_idx` (`idMesto` ASC) VISIBLE,
  CONSTRAINT `idMesta`
    FOREIGN KEY (`idMesto`)
    REFERENCES `baza`.`Mesto` (`idMesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Oglasi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Oglasi` ;

CREATE TABLE IF NOT EXISTS `baza`.`Oglasi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `naslov` VARCHAR(45) NOT NULL,
  `poslodavac` INT UNSIGNED NULL,
  `placanje` VARCHAR(45) NOT NULL,
  `plata` INT UNSIGNED NULL,
  `opis` VARCHAR(512) NULL,
  `mesto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mesto_idx` (`mesto` ASC) VISIBLE,
  INDEX `poslodavac_idx` (`poslodavac` ASC) VISIBLE,
  CONSTRAINT `poslodavac`
    FOREIGN KEY (`poslodavac`)
    REFERENCES `baza`.`firma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mesto`
    FOREIGN KEY (`mesto`)
    REFERENCES `baza`.`Mesto` (`idMesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`tags` ;

CREATE TABLE IF NOT EXISTS `baza`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`ocene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`ocene` ;

CREATE TABLE IF NOT EXISTS `baza`.`ocene` (
  `idCoveka` INT UNSIGNED NOT NULL,
  `idOcenjenog` INT UNSIGNED NOT NULL,
  `ocena` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCoveka`, `idOcenjenog`),
  INDEX `ocenjen_idx` (`idOcenjenog` ASC) VISIBLE,
  CONSTRAINT `idcovek`
    FOREIGN KEY (`idCoveka`)
    REFERENCES `baza`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ocenjen`
    FOREIGN KEY (`idOcenjenog`)
    REFERENCES `baza`.`firma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`lajkovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`lajkovi` ;

CREATE TABLE IF NOT EXISTS `baza`.`lajkovi` (
  `idCoveka` INT UNSIGNED NOT NULL,
  `idOglasa` INT UNSIGNED NOT NULL,
  `lajk` TINYINT NOT NULL,
  PRIMARY KEY (`idCoveka`, `idOglasa`),
  INDEX `Oglas_idx` (`idOglasa` ASC) VISIBLE,
  CONSTRAINT `Covek`
    FOREIGN KEY (`idCoveka`)
    REFERENCES `baza`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Oglas`
    FOREIGN KEY (`idOglasa`)
    REFERENCES `baza`.`Oglasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`poruke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`poruke` ;

CREATE TABLE IF NOT EXISTS `baza`.`poruke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCoveka` INT UNSIGNED NOT NULL,
  `idOglasa` INT UNSIGNED NOT NULL,
  `odgovor` INT NULL,
  `tekst` VARCHAR(512) NULL,
  PRIMARY KEY (`id`),
  INDEX `covek_idx` (`idCoveka` ASC) VISIBLE,
  INDEX `oglas_idx` (`idOglasa` ASC) VISIBLE,
  CONSTRAINT `covekid`
    FOREIGN KEY (`idCoveka`)
    REFERENCES `baza`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oglasa`
    FOREIGN KEY (`idOglasa`)
    REFERENCES `baza`.`Oglasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`podtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`podtags` ;

CREATE TABLE IF NOT EXISTS `baza`.`podtags` (
  `id` INT UNSIGNED NOT NULL,
  `idkategorije` INT UNSIGNED NOT NULL,
  `podkategorija` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `kategorija_idx` (`idkategorije` ASC) VISIBLE,
  CONSTRAINT `kategorija`
    FOREIGN KEY (`idkategorije`)
    REFERENCES `baza`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`tagovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`tagovi` ;

CREATE TABLE IF NOT EXISTS `baza`.`tagovi` (
  `idoglasa` INT UNSIGNED NOT NULL,
  `idtaga` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idoglasa`, `idtaga`),
  INDEX `tag_idx` (`idtaga` ASC) VISIBLE,
  CONSTRAINT `firma`
    FOREIGN KEY (`idoglasa`)
    REFERENCES `baza`.`Oglasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag`
    FOREIGN KEY (`idtaga`)
    REFERENCES `baza`.`podtags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`vlasnici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`vlasnici` ;

CREATE TABLE IF NOT EXISTS `baza`.`vlasnici` (
  `idvlasnici` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idvlasnika` INT UNSIGNED NOT NULL,
  `idfirme` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvlasnici`),
  INDEX `idvlasnik_idx` (`idvlasnika` ASC) VISIBLE,
  INDEX `idfirme_idx` (`idfirme` ASC) VISIBLE,
  CONSTRAINT `idvlasnik`
    FOREIGN KEY (`idvlasnika`)
    REFERENCES `baza`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfirme`
    FOREIGN KEY (`idfirme`)
    REFERENCES `baza`.`firma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`admins` ;

CREATE TABLE IF NOT EXISTS `baza`.`admins` (
  `id` INT UNSIGNED NOT NULL,
  `idadmin` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `admin_idx` (`idadmin` ASC) VISIBLE,
  CONSTRAINT `admin`
    FOREIGN KEY (`idadmin`)
    REFERENCES `baza`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `baza` ;

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`pretragaOglasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`pretragaOglasa` (`id` INT, `naslov` INT, `placanje` INT, `Mesto` INT, `name` INT, `podkategorija` INT, `tag` INT);

-- -----------------------------------------------------
-- View `baza`.`pretragaOglasa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`pretragaOglasa`;
DROP VIEW IF EXISTS `baza`.`pretragaOglasa` ;
USE `baza`;
CREATE  OR REPLACE VIEW `pretragaOglasa` AS
select o.id,o.naslov,o.placanje,m.Mesto,f.name,p.podkategorija,ts.tag from oglasi o join mesto m on o.mesto = m.idMesto join firma f on o.poslodavac = f.id join tagovi t on o.id = t.idoglasa join podtags p on t.idtaga = p.id join tags ts on p.idkategorije = ts.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

Create USER 'MyLogin'@'localhost' identified by '123123';
Grant ALL privileges on baza .* to 'MyLogin'@'localhost';