-- MySQL Script generated by MySQL Workbench
-- Mon Sep 20 09:26:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `baza` ;

-- -----------------------------------------------------
-- Table `baza`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`tags` ;

CREATE TABLE IF NOT EXISTS `baza`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Mesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Mesto` ;

CREATE TABLE IF NOT EXISTS `baza`.`Mesto` (
  `idMesto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMesto`),
  UNIQUE INDEX `idMesto_UNIQUE` (`idMesto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `baza`.`Korisnik` (
  `idKorisnik` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(50) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Poslodavac` TINYINT NOT NULL,
  `Admin` TINYINT NOT NULL,
  `idmesta` INT UNSIGNED NOT NULL,
  `Opis` VARCHAR(512) NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `mes_idx` (`idmesta` ASC) VISIBLE,
  CONSTRAINT `mest`
    FOREIGN KEY (`idmesta`)
    REFERENCES `baza`.`Mesto` (`idMesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Oglas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Oglas` ;

CREATE TABLE IF NOT EXISTS `baza`.`Oglas` (
  `idOglas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCoveka` INT UNSIGNED NOT NULL,
  `Naslov` VARCHAR(50) NOT NULL,
  `Tip` TINYINT UNSIGNED NOT NULL,
  `Plata` INT UNSIGNED NULL,
  `Opis` VARCHAR(512) NULL,
  `Mesto` INT UNSIGNED NULL,
  PRIMARY KEY (`idOglas`),
  INDEX `Gazda_idx` (`idCoveka` ASC) VISIBLE,
  INDEX `mes_idx` (`Mesto` ASC) VISIBLE,
  CONSTRAINT `Gazda`
    FOREIGN KEY (`idCoveka`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mess`
    FOREIGN KEY (`Mesto`)
    REFERENCES `baza`.`Mesto` (`idMesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`lajkovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`lajkovi` ;

CREATE TABLE IF NOT EXISTS `baza`.`lajkovi` (
  `idCoveka` INT UNSIGNED NOT NULL,
  `idOglasa` INT UNSIGNED NOT NULL,
  `lajk` TINYINT NOT NULL,
  PRIMARY KEY (`idCoveka`, `idOglasa`),
  INDEX `Oglas_idx` (`idOglasa` ASC) VISIBLE,
  CONSTRAINT `Covek`
    FOREIGN KEY (`idCoveka`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Oglas`
    FOREIGN KEY (`idOglasa`)
    REFERENCES `baza`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`poruke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`poruke` ;

CREATE TABLE IF NOT EXISTS `baza`.`poruke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCoveka` INT UNSIGNED NOT NULL,
  `idOglasa` INT UNSIGNED NOT NULL,
  `odgovor` INT NULL,
  `tekst` VARCHAR(512) NULL,
  PRIMARY KEY (`id`),
  INDEX `covekid_idx` (`idCoveka` ASC) VISIBLE,
  INDEX `oglasa_idx` (`idOglasa` ASC) VISIBLE,
  CONSTRAINT `covekid`
    FOREIGN KEY (`idCoveka`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oglasa`
    FOREIGN KEY (`idOglasa`)
    REFERENCES `baza`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`podtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`podtags` ;

CREATE TABLE IF NOT EXISTS `baza`.`podtags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idkategorije` INT UNSIGNED NOT NULL,
  `podkategorija` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `kategorija_idx` (`idkategorije` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `kategorija`
    FOREIGN KEY (`idkategorije`)
    REFERENCES `baza`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`tagovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`tagovi` ;

CREATE TABLE IF NOT EXISTS `baza`.`tagovi` (
  `idoglasa` INT UNSIGNED NOT NULL,
  `idtaga` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idoglasa`, `idtaga`),
  INDEX `tag_idx` (`idtaga` ASC) VISIBLE,
  CONSTRAINT `firma`
    FOREIGN KEY (`idoglasa`)
    REFERENCES `baza`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag`
    FOREIGN KEY (`idtaga`)
    REFERENCES `baza`.`podtags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Telefoni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Telefoni` ;

CREATE TABLE IF NOT EXISTS `baza`.`Telefoni` (
  `idKorisnika` INT UNSIGNED NOT NULL,
  `Broj` VARCHAR(15) NOT NULL,
  INDEX `Covek_idx` (`idKorisnika` ASC) VISIBLE,
  PRIMARY KEY (`idKorisnika`, `Broj`),
  CONSTRAINT `kevoc`
    FOREIGN KEY (`idKorisnika`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Ocena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Ocena` ;

CREATE TABLE IF NOT EXISTS `baza`.`Ocena` (
  `IdCoveka` INT UNSIGNED NOT NULL,
  `IdOcenjenog` INT UNSIGNED NOT NULL,
  `Ocena` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdCoveka`, `IdOcenjenog`),
  INDEX `IdOcenjog_idx` (`IdOcenjenog` ASC) VISIBLE,
  CONSTRAINT `IdCoveka`
    FOREIGN KEY (`IdCoveka`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdOcenjog`
    FOREIGN KEY (`IdOcenjenog`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`Prijave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`Prijave` ;

CREATE TABLE IF NOT EXISTS `baza`.`Prijave` (
  `idCovek` INT UNSIGNED NOT NULL,
  `idOglas` INT UNSIGNED NOT NULL,
  `CV` VARCHAR(512) NULL,
  PRIMARY KEY (`idCovek`, `idOglas`),
  INDEX `po_idx` (`idOglas` ASC) VISIBLE,
  CONSTRAINT `co`
    FOREIGN KEY (`idCovek`)
    REFERENCES `baza`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `po`
    FOREIGN KEY (`idOglas`)
    REFERENCES `baza`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `baza` ;

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`SveOKorisniku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`SveOKorisniku` (`idkorisnik` INT, `ime` INT, `email` INT, `username` INT, `password` INT, `opis` INT, `mesto` INT, `petice` INT, `cetvorke` INT, `trojke` INT, `dvojke` INT, `jedinice` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`petice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`petice` (`broj` INT, `idOcenjenog` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`cetvorke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`cetvorke` (`broj` INT, `idOcenjenog` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`trojke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`trojke` (`broj` INT, `idOcenjenog` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`dvojke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`dvojke` (`broj` INT, `idOcenjenog` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`jedinice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`jedinice` (`broj` INT, `idOcenjenog` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`likes` (`broj` INT, `idoglasa` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`dislikes` (`broj` INT, `idoglasa` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`SveOOglasu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`SveOOglasu` (`idoglas` INT, `ime` INT, `naslov` INT, `tip` INT, `plata` INT, `opis` INT, `mesto` INT, `likes` INT, `dislikes` INT);

-- -----------------------------------------------------
-- Placeholder table for view `baza`.`slozeniTagovi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baza`.`slozeniTagovi` (`idoglasa` INT, `concat(ta.tag,"-",pt.podkategorija)` INT);

-- -----------------------------------------------------
-- View `baza`.`SveOKorisniku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`SveOKorisniku`;
DROP VIEW IF EXISTS `baza`.`SveOKorisniku` ;
USE `baza`;
CREATE  OR REPLACE VIEW `SveOKorisniku` AS
select k.idkorisnik,k.ime ,k.email,k.username,k.password,k.opis,m.ime as mesto,p.broj as petice,c.broj as cetvorke,t.broj as trojke,d.broj as dvojke,j.broj as jedinice
from korisnik k join mesto m on k.idmesta = m.idmesto
left join petice p on k.idkorisnik = p.idOcenjenog
left join cetvorke c on k.idkorisnik = c.idOcenjenog
left join trojke t on k.idkorisnik = t.idOcenjenog
left join dvojke d on k.idkorisnik = d.idOcenjenog
left join jedinice j on k.idkorisnik = j.idOcenjenog;

-- -----------------------------------------------------
-- View `baza`.`petice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`petice`;
DROP VIEW IF EXISTS `baza`.`petice` ;
USE `baza`;
CREATE  OR REPLACE VIEW `petice` AS
select count(ocena) as broj, idOcenjenog
from Ocena
where ocena=5
group by idOcenjenog;

-- -----------------------------------------------------
-- View `baza`.`cetvorke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`cetvorke`;
DROP VIEW IF EXISTS `baza`.`cetvorke` ;
USE `baza`;
CREATE  OR REPLACE VIEW `cetvorke` AS
select count(ocena) as broj , idOcenjenog
from Ocena
where ocena=4
group by idOcenjenog;

-- -----------------------------------------------------
-- View `baza`.`trojke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`trojke`;
DROP VIEW IF EXISTS `baza`.`trojke` ;
USE `baza`;
CREATE  OR REPLACE VIEW `trojke` AS
select count(ocena) as broj , idOcenjenog
from Ocena
where ocena=3
group by idOcenjenog;

-- -----------------------------------------------------
-- View `baza`.`dvojke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`dvojke`;
DROP VIEW IF EXISTS `baza`.`dvojke` ;
USE `baza`;
CREATE  OR REPLACE VIEW `dvojke` AS
select count(ocena) as broj , idOcenjenog
from Ocena
where ocena=2
group by idOcenjenog;

-- -----------------------------------------------------
-- View `baza`.`jedinice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`jedinice`;
DROP VIEW IF EXISTS `baza`.`jedinice` ;
USE `baza`;
CREATE  OR REPLACE VIEW `jedinice` AS
select count(ocena) as broj, idOcenjenog
from Ocena
where ocena=1
group by idOcenjenog;

-- -----------------------------------------------------
-- View `baza`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`likes`;
DROP VIEW IF EXISTS `baza`.`likes` ;
USE `baza`;
CREATE  OR REPLACE VIEW `likes` AS
select count(lajk) as broj, idoglasa
from lajkovi
where lajk=true
group by idoglasa;

-- -----------------------------------------------------
-- View `baza`.`dislikes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`dislikes`;
DROP VIEW IF EXISTS `baza`.`dislikes` ;
USE `baza`;
CREATE  OR REPLACE VIEW `dislikes` AS
select count(lajk) as broj, idoglasa
from lajkovi
where lajk=false
group by idoglasa;

-- -----------------------------------------------------
-- View `baza`.`SveOOglasu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`SveOOglasu`;
DROP VIEW IF EXISTS `baza`.`SveOOglasu` ;
USE `baza`;
CREATE  OR REPLACE VIEW `SveOOglasu` AS
select o.idoglas,k.ime,o.naslov,o.tip,o.plata,o.opis,m.ime as mesto,l.broj as likes,d.broj as dislikes
from oglas o join korisnik k on o.idcoveka = k.idkorisnik
join mesto m on o.mesto = m.idmesto
left join likes l on o.idoglas = l.idoglasa
left join dislikes d on o.idoglas = d.idoglasa;

-- -----------------------------------------------------
-- View `baza`.`slozeniTagovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`slozeniTagovi`;
DROP VIEW IF EXISTS `baza`.`slozeniTagovi` ;
USE `baza`;
CREATE  OR REPLACE VIEW `slozeniTagovi` AS
select t.idoglasa,concat(ta.tag,"-",pt.podkategorija)
from tagovi t join podtags pt on t.idtaga = pt.id
join tags ta on pt.idkategorije = ta.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO MESTO(ime) values('Beograd');
INSERT INTO MESTO(ime) values('Novi Sad');
INSERT INTO MESTO(ime) values('Nis');
INSERT INTO MESTO(ime) values('Kragujevac');
INSERT INTO MESTO(ime) values('Pristina');
INSERT INTO MESTO(ime) values('Subotica');
INSERT INTO MESTO(ime) values('Zrenjanin');
INSERT INTO MESTO(ime) values('Pancevo');
INSERT INTO MESTO(ime) values('Cacak');
INSERT INTO MESTO(ime) values('Krusevac');
INSERT INTO MESTO(ime) values('Kraljevo');
INSERT INTO MESTO(ime) values('Novi Pazar');
INSERT INTO MESTO(ime) values('Smederevo');
INSERT INTO MESTO(ime) values('Leskovac');
INSERT INTO MESTO(ime) values('Uzice');
INSERT INTO MESTO(ime) values('Vranje');
INSERT INTO MESTO(ime) values('Valjevo');
INSERT INTO MESTO(ime) values('Sabac');
INSERT INTO MESTO(ime) values('Sombor');
INSERT INTO MESTO(ime) values('Pozarevac');
INSERT INTO MESTO(ime) values('Pirot');
INSERT INTO MESTO(ime) values('Zajecar');
INSERT INTO MESTO(ime) values('Kikinda');
INSERT INTO MESTO(ime) values('Sremska Mitrovica');
INSERT INTO MESTO(ime) values('Jagodina');
INSERT INTO MESTO(ime) values('Vrsac');
INSERT INTO MESTO(ime) values('Bor');
INSERT INTO MESTO(ime) values('Loznica');
INSERT INTO MESTO(ime) values('Aleksinac');
INSERT INTO MESTO(ime) values('Aleksandrovac');
INSERT INTO MESTO(ime) values('Apatin');
INSERT INTO MESTO(ime) values('Batajnica');
INSERT INTO MESTO(ime) values('Bela Crkva');
INSERT INTO MESTO(ime) values('Belo Polje');
INSERT INTO MESTO(ime) values('Bujanovac');
INSERT INTO MESTO(ime) values('Vrnjacka Banja');
INSERT INTO MESTO(ime) values('Vrbas');
INSERT INTO MESTO(ime) values('Gornji Milanovac');
INSERT INTO MESTO(ime) values('Despotovac');
INSERT INTO MESTO(ime) values('Ivanjica');
INSERT INTO MESTO(ime) values('Kladovo');
INSERT INTO MESTO(ime) values('Kostolac');
INSERT INTO MESTO(ime) values('Kula');
INSERT INTO MESTO(ime) values('Kucevo');
INSERT INTO MESTO(ime) values('Lazarevac');
INSERT INTO MESTO(ime) values('Lebane');
INSERT INTO MESTO(ime) values('Ljig');
INSERT INTO MESTO(ime) values('Mladenovac');
INSERT INTO MESTO(ime) values('Negotin');
INSERT INTO MESTO(ime) values('Odzaci');
INSERT INTO MESTO(ime) values('Palic');
INSERT INTO MESTO(ime) values('Pec');
INSERT INTO MESTO(ime) values('Prizren');
INSERT INTO MESTO(ime) values('Prokuplje');
INSERT INTO MESTO(ime) values('Ruma');
INSERT INTO MESTO(ime) values('Raca');
INSERT INTO MESTO(ime) values('Svilajnac');
INSERT INTO MESTO(ime) values('Sokobanja');
INSERT INTO MESTO(ime) values('Surcin');
INSERT INTO MESTO(ime) values('Trstenik');
INSERT INTO MESTO(ime) values('Topola');
INSERT INTO MESTO(ime) values('Cicevac');
INSERT INTO MESTO(ime) values('Cuprija');
INSERT INTO MESTO(ime) values('Ub');
INSERT INTO MESTO(ime) values('Sabac');
INSERT INTO MESTO(ime) values('Sid');

INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ("admin","admin","admin","admin@admin.admin",1,true,true,'admin');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('UBISOFT - Novi Sad', 'MilicaM', 'milica01', 'milica.medakovic@gmail.com', 1, true, false,'Ubisoft developing center in Serbia(Novi Sad)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Xtechno', 'MladenK', 'mladen02', 'mladen.krstic@gmail.com', 2, true, false,'Novonastala firma smestana Novi Sad');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Marko Pavlovic', 'MarkoP', 'marko03', 'marko.pavlovic@gmail.com', 3, false, false,'Dipl. informatica - Fin Kragujevac(Softversko inzenjerstvo)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Biro - Nis' , 'OgnjenN', 'ognjen04', 'ognjen.negic@gmail.com', 3, true, false,'Drzavna agencija za zapsljavanje Nis');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('DeluxeResort', 'FilipI', 'filip05', 'filip.ilic@gmail.com', 4, true, false,'Apartmani na Zlatiboru sa poslom toko cele godine');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Pekara Sreca', 'DanicaL', 'danica06', 'danica.lazarevic@gmail.com', 4, true, false,'Sreca lokalna pekara u Cacku');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Jelena Gajic', 'JelenaG', 'jelena07', 'jelena.gajic@gmail.com', 5, false, false,'Dipl. ekonomista - Ekonomski fakultet Beograd');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Katarina Ivanov', 'KatarinaI', 'katarina08', 'katarina.ivanov@gmail.com', 1, false, false,'Dipl. toksikolog ');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Luka Jolic', 'LukaJ', 'luka09', 'luka.jolic@gmail.com', 1, false, false,'Dipl. biolog - PMF Kragujevac');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Dusan 	Tomic', 'DusanT', 'dusan10', 'dusan.tomic@gmail.com', 2, false, false,'Visa strukovna skola - Smer masinsko inzinjerstvo');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Stefan Nenadovic', 'StefanN', 'stefan11', 'stefan.nenadovic@gmail.com', 2, false, false,'Dipl. matematicar sa visegodisnjim iskustvom u ekonomiji');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Janko Petrovic', 'JankoP', 'janko12', 'janko.petrovic@gmail.com', 3, false, false,'Ekonomista sa radnim iskustvom');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Ivan Markovic', 'IvanM', 'ivan13', 'ivan.markovic@gmail.com', 4, false, false,'Web dizajner sa sertifikatom ITAcademia');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Lazar Petkovic', 'LazarP', 'lazar14', 'lazar.petkovic@gmail.com', 12, false, false,'Vozac sa visegodisnjim iskustvom i posedovanjem (B,C,CE kategorije)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Danilo Jankovic', 'DaniloJ', 'danilo15', 'daniko.jankovic@gmail.com', 8, false, false,'Turisticki vodic voljan za saradnju');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Darko Stosic', 'DarkSt', 'darko77', 'darko.stosic@gmail.com', 4, false, false,'Bravar/Varioc');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Aleksandar Petkovic', 'Aleks15', 'aleksandar15', 'petkovic.a@gmail.com', 3, false, false,'Filoloski fakultet - smer Engleski jezik');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Stefan Nemanjic', 'Stefan7', 'sifra1389', 'nemanja7@gmail.com', 55, false, false,'Student - PMF Kragujevac(informatika)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Aleksandar Rodic', 'AleksR', 'olovka14', 'rodic.aleks@gmail.com',14 , false, false,'Samouki automehanicar sa visegodisnjim iskustvom');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('SpanishTranslate', 'Nikolina19', 'nikolina1234', 'nikolina.cvetix@gmail.com', 22, false, false,'Filoloski fakultet - spanski jezik');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Jovana Markovic', 'Joka11', 'jovanica1567', 'jovanica.mark@gmail.com', 13, false, false,'Penzionisani profesor engleskog jezika');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Stefan Radovanovic', 'Radule19', 'radradrad123', 'steff@gmail.com', 4, false, false,'Samouki web dizajner sa iskustvom na freelance platformama');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Petar Nikolic', 'PetarNi', 'stanovo100', 'perica.ni@gmail.com', 7, false, false,'Vredan i Precizan Varioc pocetnik voljan da napreduje');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Nikola Jovanovic', 'Joker7', 'password17', 'joker.joker@gmail.com', 11, false, false,'Iskusni poljoprivrednik sposoban za sve radove na selu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Mihailo Kadic', 'Miketa12', 'miketa.pass', 'mihailo.kadic12@gmail.com', 22, false, false,'Dipl. pravnik - Pravni fakultet Novi Sad');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Milan Petrovic', 'MilanPtrvc', 'zizzza33', 'milance.ptrvc@gmail.com', 44, false, false,'Dipl. pravnik - Pravni fakultet Kragujevac');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Ivana Arsic', 'Arsicka22', 'webdizajn1345', 'arsicka.iv@gmail.com', 21,false, false,'Iskusna vaspitacica sa zavrsenom visom skolom');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Petar Nikodijevic', 'Nikodije8', 'niki1niki2', 'nikodije8@gmail.com', 22, false, false,'Student informatike ETF(Softversko inzinjerstvo)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Turizam Srbije', 'DacaDju', 'djuricca', 'dan.dju@gmail.com', 7, true, false,'Kompanija u potrazi za mladim i ambicioznim radnicima');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Vuk Ivanovic', 'VukelaCa', 'Cacak2000', 'vukivan@gmail.com', 6, false, false,'Vredan fizikalni radnik sposoban za veliki broj poslova');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Jovan Radic', 'JocaRad', 'RadeleRadele', 'joca.radele@gmail.com', 16, false, false,'Advokat sa visegodisnjim radnim stazom');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('FastFood Carolija', 'VukicaK', 'Kockica7', 'vukela.koc@gmail.com', 25, true, false,'Najbolji Fastfood u Beogradu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Milorad Draskovic', 'MikiDra', 'banjaluka92', 'milorad.dra@gmail.com', 64, false, false,'Poljoprivrednik i Mehanicar');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Milan Zivkovic', 'Zile.Kg', 'radijator223', 'milance.zile@gmail.com', 18, false, false,'Nezaposleni masinski inzenjer');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Privatna bolnica Beograd', 'KrleJas', 'vi.jasminica', 'jasminica.krle@gmail.com', 36, true, false,'Bolnica sa najboljim i najiskusnijim lekarima');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Kafana Veselo Drustvo-Kraljevo', 'ShoneStri', 'strikovic55', 'nebojsa.shone@gmail.com', 55, true, false,'Idealna kafana za sve vrste proslava');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Kristina Pavlovic', 'Kiki77', 'kristinaaa', 'kristina.pavl@gmail.com', 66, false, false,'Dipl. biohemicar');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Nevena Petkovic', 'Nenaaa', 'nenica222', 'nena.petkovic@gmail.com', 21, false, false,'Mlada i ambiciozna ekonomistkinja');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Anastasija Janjic', 'AnicaJa', 'jajaja99', 'anica.ja@gmail.com', 12, false, false,'Visegodisnje iskustvo kao medicniski tehnicar u inostranstvu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Ksenija Pantelic', 'KsendziPa', 'albatros666', 'kse.pan@gmail.com', 3, false, false,'Penzionisana profesorka francuskog jezika');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Obdaniste Lane', 'IkacDav', 'ikica.drom', 'dav.ilija@gmail.com', 1, true, false,'Prijatan i cist ambijent za vase malisane');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Cerak gradsko stovariste', 'CirkovicNi', 'cirule.nidza', 'cirko.nikola@gmail.com', 24, true, false,'Najpovoljniji u gradu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Fabrika teskih metala', 'StankoAle', 'lebronjames23', 'stankoviccc@gmail.com', 8, true, false,'Fabrika smestena u Valjevu u potrazi za radnicima');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Klinicki centar Kragujevac', 'MegiSim', 'bevrlyhills', 'megica.simic@gmail.com', 19, true, false,'Centar za zaposljavanje - KC Kragujevac');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Domacin', 'BanovicJa', 'markokraljevic', 'banoviccc.ja@gmail.com', 6, true, false,'Poljorpivredna apoteka Domacin- Sabac');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('UBISOFT - NoviSad', 'FikiDe', 'dendula.sifra', 'denic.fiki@gmail.com', 36, true, false,'Ubisoft developing center in Serbia(Novi Sad)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Panorama aqualux', 'Kristina77', 'novisad.ns', 'kristina.ns@gmail.com', 25, true, false,'Potrebni radnici volji za rad u dinamicnoj atmosferi u prijatnom ambijentu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Teodora Hadzic', 'TeaTea', 'teodorica..ss', 'tea.hadz@gmail.com', 15, false, false,'Sposobna za obavljanje svih administrativnih poslova');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Nebojsa Stojkovic', 'Nesa100', 'punastotka', 'nebojsa100@gmail.com', 13, false, false,'Visegodisnja karijera kao uspesni administrator racunarskih mreza');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Kristijan Sekulovic', 'KikiSek', 'kristijance45', 'kikiSek@gmail.com', 6, false, false,'Samouki dizajner sposoban za rad u photoshopu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Jankovic', 'BogiBog', 'jankovibogdan1', 'bogdan.jankovic@gmail.com', 9, true, false,'Novonastala advokatska kancelarija Jankovic zaposljava mlade pranike');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Envoy', 'RadeLju', 'pariz2017', 'radivoje.ljub@gmail.com', 27, true, false,'Hotel Envoy smesten u okolini Beograda');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Aleksandar Kostic', 'Kole111', 'frankfurt17', 'coa.kole@gmail.com', 60, false, false,'Sposoban za rad prevodioca sa nemackog,engleskog na srpski jezik');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Filip Markovic', 'Filipe00', 'fikica123', 'filipMar@gmail.com', 40, false, false,'Freelance dizajner u potrazi za stalnim poslom, posedovanje vestina u photospou i corelu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Mateja Zoric', 'MataZo', 'Zoro111', 'mata.zo@gmail.com', 23, false, false,'Dipl. elektrotehnicar');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Pavle Miljkovic', 'MiljkoPa', 'pa102030', 'paki.miljko@gmail.com', 10, false, false,'Ambiciozni Dipl. pravnik');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Cvecara Narcis', 'jokicka3', 'janajokjanajok', 'janica.jokic@gmail.com', 3, true, false,'Cvecara Narcis zbog obima posla u potraznji za novim radnicima');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('StudyAbroadSerbia', 'Savke90', 'total90kop', 'milos.savic.study@gmail.com', 11, true, false,'StudyAbroadSerbia company that helps young people to chase dreams');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Farma pilica', 'BranaLa', 'djurdjevdan96', '@gmail.com', 7, true, false,'Zbog obima posla potrebno jos radnika, pozeljno iskustvo');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Stefan Brankovic', 'Br4kovic', 'steleBra', 'br4ankovic@gmail.com', 33, false, false,'Programer pocetnik sposoban za rad u pythonu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Crvenkapa', 'OljaGeg', 'oljica2504', 'gegovickka@gmail.com', 14, true, false,'Direktorka obdanista Traze se vredne osobe sposobne za rad sa decom u Kragujevackom obdanistu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Danica Mrkonjic', 'MrkonjaDan', 'dannnica93', 'mrkonjic.danica@gmail.com', 36, true, false,'Mastalica - Beograd trenutno u potrazi za novim radnicima');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('LearnEnglishSerbia', 'JasarUr', 'jjjasssarrr', 'jasarevicu@gmail.com', 30, true, false,'Private Serbian school LearnEnglishSerbia - Pristina');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Sinisa Djordjevic', 'SikiDj', 'djnansi', 'dj.sinisa@gmail.com', 39, false, false,'Pocetnik programer zeljan za napretkom,sposoban za rad javi');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Vasilije Milic', 'VasaMil91', 'crvenazvezda91', 'vasamil.@gmail.com', 41, true, false,'Otvorene pozicije za administrativan rad');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Valentina Hristic', 'TinceHri', 'tinicahrist', 'hri.valentina@gmail.com', 5, false, false,'Samouka kuvarica sa iskusnim radom u restoranu');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Jovana Poskoric', 'PskorJo', 'poskoricaJo', 'poskoric.jo@gmail.com', 6, false, false,'Dipl. Ekolog - PMF Kragujevac');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('DataCen', 'Dima25', 'dddiiimmmaaa', 'dimovicdi@gmail.com', 9, true, false,'DataCen looking for young workers');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('TradeCell', 'KostaNik', 'partizan92', 'kostanikolic@gmail.com', 12, true, false,'TradeCell finansijska kompanija');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Mozart', 'TanjaDan27', 'takica14', 'tanjadan@gmail.com', 3, true, false,'Muzicka skola Mozzart zaposljava iskusne muzicare spremne za rad sa decom');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Nikola Pantic', 'Pantela1', 'dzonipantic100', 'pppantela@gmail.com', 34, true, false,'Penzionisani profesor matematike sposbna za drzanje casova (osnovna i srednja skola)');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('PZP Kladovo', 'StraleKoc', 'paradajz10', 'stahinja.koc@gmail.com', 41, true, false,'Preduzece za puteve -  Kladovo');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('Filip Prodanovic', 'ProFiki10', 'sklekovi89', 'prodanovicc@gmail.com', 65, false, false,'Vaspitac sa iskustvom u radu sa decom');
INSERT INTO KORISNIK(Ime,Username,Password,Email,idmesta,Poslodavac,Admin,Opis) values ('BerlinCall', 'Jocika89', 'crvenaruza666', 'jocika.ata@gmail.com', 55, true, false,'BerlinCall german company with office in Serbia');

insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (1, 'Java Developer', false, 2000, 'We are looking for senior developers. We are a team with 20 years of experience in the industry with multiple branches. Our plan is to emply more then 50 developers in one year time.', 1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (1, 'Python Developer', false, 2200, 'We are looking for senior developers. We are a team with 20 years of experience in the industry with multiple branches. Our plan is to emply more then 50 developers in one year time.', 1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (1, 'PHP Developer', false, 1800, 'We are looking for senior developers. We are a team with 20 years of experience in the industry with multiple branches. Our plan is to emply more then 50 developers in one year time.',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (64, 'Nastavnik engleskog jezika' , false, 450, 'Trenutno pripremamo našu školu za novu akademsku godinu kako bi postala najbolja opcija za učenje stranih jezika za decu. Prijavite se odmah, tako da ste spremni da započnete predavanje od pocetka Septembra!', 2);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (75, 'Nastavnik nemackog jezika', true, 450, 'Trenutno pripremamo našu školu za novu akademsku godinu kako bi postala najbolja opcija za učenje stranih jezika za decu. Prijavite se odmah, tako da ste spremni da započnete predavanje od pocetka Septembra!', 2);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (73, 'Automehanicar', false, 500, 'Zbog povecanog obima posla raspisujemo konkurs za radnu poziciju : Automehanicar za servisiranje vozila iz programa Renault i Nissan', 3);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (52, 'Advokat - saradnik', true, 800, 'Mi smo advokatska kancelarija koja veruje u rast i stalno usavrsavanje. Zainteresovani smo da prosirimo tim sa novim kolegama koji se pronalaze u našim vrednostima, dele nase ambicije i predanost klijentima.',3);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (44, 'Projektant proizvoda tapaciranog nameštaja' ,true, 800, 'Nasem timu potrebni su kandidati za poziciju Projektant proizvoda tapaciranog namestaja, ciji opis posla obuhvata : izradu kalkulacija, konstrukcija proizvoda, definisanje definisanje konstrukcijske dokumentacije...',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (36, 'Medicinska sestra/tehničar', true, 500,'Zbog prosirenja posla potrebno nam je medicinsko osoblje: Medicinska sestra/tehnisar.',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (75, 'Office administrator', false, 700, 'Kao generalni uvoznik i distributer brendova  Energizer, Varte, Firecell i Mustang, imamo najsiru i najkompletniju ponudu akumulatora u Republici Srbiji. U cilju razvoja poslovanja, oglasavamo potrebu za sledesim radnim mestom: OFFICE ADMINISTRATOR',12);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (3, 'Java Developer', false, 1800, 'Potreban java programer koji je voljan da radi u dinamicnom i profesionalnom okruzenju, pozeljno je da poseduje radno iskustvo u programskom jeziku Java',2);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (4, 'Web dizajner', false, 1200, 'KgDesign je novonastala kompanija koja trenutno ima otvorene pozicije za mlade i vredne veb dizajnere, bilo kakvo iskustvo je pozeljno ali ne i neophodno. Tehnologije koje su pozeljno za kandidate su (HTML,CSS,JavaScript,PHP i sl)',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (69, 'Data Analyst Intern', true, 900, 'We are looking for a motivated, talented and committed Data Analyst Intern to join our Data Science team within Customer Relationship Management department.',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (69, 'Quality Analyst', false, 1000, 'Attention talented individual! As Switzerland’s leading digital hub, we provide our media and platforms with enabling technology solutions, to drive their businesses. We stand for interdisciplinary collaboration, innovation, and dynamic development.',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (47, 'Lead Programmer', false, 1000, 'Ubisoft Belgrade is looking for a talented Lead Programmer to join our growing team of 200 people! Our expectations of a Lead Programmer are more people oriented. Technical expertise in C++ and the experience in the gaming industry is a plus but it’s not necessary.',2);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (36, 'Negovatelj/negovateljica', true, 450, 'Tražimo negovatelje/negovateljice za rad u Nemačkoj, Austriji, Holandiji, Irskoj, Belgiji i Velikoj Britaniji.',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (45, 'Medicinska sestra', true, 500, 'Klinicki centar u Kragujevcu raspisuje konkurs za sva zainteresovana lica koja imaju iskustva u radu kao medicinskog tehnicara',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (42, 'Medicinska sestra', true, 470, 'POTREBAN/NA MEDICINSKA SESTRA-VASPITAČ, polu ili puno radno vreme u privatnom vrtiću',6);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (48, 'Recepcioner/ka', false, 400, '"Panorama Aqualux" je otvoren 2015. godine, na Kamenjaru (Novi Sad), na samoj obali Dunava, u mirnom kraju grada. Lokacija je izuzetna zbog toga što gosti u svakom trenutku mogu uživati u prelepoj panorami Fruške Gore i Dunava.',2);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (27, 'Recepcioner', true, 500, 'Envoy Hotel se nalazi u samom centru Beograda, na mestu nekadašnje australijske ambasade u Čika Ljubinoj ulici broj 13. Ušuškan u tihoj pešačkoj oazi usred gradske vreve, Envoy je savršen izbor za modernog putnika koji traži visoki kvalitet i besprekornu uslugu',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (5, 'Menadžer bukinga', false, 400, 'Tražimo visprenu, odgovornu i dobro organizovanu osobu da se pridruži našem timu, na radu na rezervacijama apartmanskog smeštaja u Nisu.Potreban nam je: Menadžer bukinga (Nis)',3);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (55, 'Radnik u turističkoj agenciji i menjačnici', false, 450, 'Trendy Travel je turistička agencija koja se bavi receptivnim turiznom, kao i organizacijom seminara, kongresa, izleta i mnogih drugih skupova.U okviru agencije obavljamo menjačke poslove, kao i poslove platnog prometa.',10);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (30, 'Turisticki vodic', false, 700, 'Potreban iskusan,vredan turisticki vodic koji detaljno poznaje sve turisticke predele u Srbiji',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (37, 'Konobar - šanker', false, 400, 'Posluživanje, rad u šanku, higijena radnog prostora, timski rad.',11);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (33, 'Pizza majstor', false, 420, 'Potrebne komunikativne i brze osobe u radu.,Brza hrana Poncho potrebni radnici m/ž pizza - majstor',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (33, 'Radnik za pripremu hrane', true, 450, 'Tražimo radnika za pripremu pasti, rižota i tortilja po standardnoj recepturi i normativima. Nije neophodna diploma kuvara, prednost ima iskustvo u radu. Radi se 6 dana nedeljno po smenama prva i druga.',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (37, 'Barmen', false, 400, 'Priprema napitaka i izdavanje pića i drugih porudžbina iz domena rada sekcije bara. Vođenje brige o higijeni radnog mesta i pripadajuće opreme i alata.',11);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (37, 'Pomoćni radnik u kuhinji', false, 300, 'Rad na fritezi, filovanju, palačinkari, pravljenju lepinja, pasti, poštujući utvrđene normative.Odlaganje i pakovanje namirnica na mesta propisana za to.',11);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (7, 'Radnica u prodaji', false, 320, 'Radnica u prodaji peče i prodaje pite i kiflice i brine se o higijeni prodajnog prostora.',9);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (43, 'Varilac/bravar', true, 600, 'Potreban bravar/varilac za proizvodnju i montažu sportske opreme i konstrukcija.',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (44, 'Radnik u proizvodnji plastike', true, 400, 'Izrada proizvoda i delova od plastike,Vredan, odgovoran, precizan i tačan.Plata se isplaćuje na nedeljnom nivou.',17);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (44, 'Zavarivač TIG/MIG/MAG', false, 500, 'Zavarivanje sklopova čeličnih konstrukcija iz pozicija limova, cevi i profila MIG/MAG postupkom.Samostalno izvodi zavarivanje na radnom komadu i zavarivanje podsklopova i sklopova po radnom nalogu',17);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (60, 'Radnik na farmi tovnih pilića', false, 550, 'Kontrola rada opreme, obilazak i održavanje kruga farme, isporuka tovnih pilića,u Pavlovcima',55);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (46, 'Diplomirani inženjer zaštite bilja', false, 550, 'Potreban radnik za rad u poljoprivrenoj apoteci.Neophodna stručna sprema. Diplomirani inženjer zaštite bilja VSS ili strukovni inženjer agronomije za zaštitu bilja.',18);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (60, 'Radnik na farmi', false, 450, 'Potreban radnik za rad na farmi krava (okolina Šapca). Stan obezbeđen, plata po dogovoru.Sve informacije na telefon',55);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (58, 'Cvećar-cvećarka', false, 430, 'Poželjno radno iskustvo u cvecarstvu i pravljenju aranžmana. Poželjno radno iskustvo na istim ili sličnim poslovima',1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (63, 'Vaspitač', true, 500, 'P.P.U. Maštalica proširuje svoj tim, zbog povećanog obima posla, potreban: VASPITAČ',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (59, 'Konsultant za školovanje u inostranstvu', false, 800, 'Poslujemo od 1982. godine, a danas Egida ima 4 kancelarije (Novi Sad, Beograd, Podgorica i Majami), a savetovanja radimo i online.Tražimo kolegu ili koleginicu za rad na poziciji: Konsultant za školovanje u inostranstvu',2);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (64, 'Online English Teacher', false, 450, 'Organize your life and earn by working from any location with totally flexible working hours and schedule.',5);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (64, 'Profesor engleskog jezika', false, 500, 'Škola engleskog jezika Tom & Emma radi na Banovom brdu od 1993. godine i jedina je škola u Srbiji koja je član evropskog udruženja škola stranih jezika',5);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (62, 'Saradnik za rad i edukaciju dece', false, 420, 'Za sve one koji vole da igraju i da se igraju sa decom uzrasta od 3-6 godina raspisujemo konkurs za poziciju Saradnik za rad i edukaciju dece (Kragujevac)',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (62, 'Vaspitač/vaspitačica', false, 440, 'Malom raspevanom vrtiću, potreban/na je vaspitač/ica za rad na neodređeno vreme.',4);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (66, 'Radnik za rad u apartmanima', false, 400, 'Potreban radnik za obavljanje organizacionih poslova. Radno mesto obuhvata prijem poziva, evidentiranje rezervacija, prijem gostiju, organizaciju rada sobarica i sitne administrativne poslove.', 1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (41, 'Administrativni saradnik', false, 410, 'Priprema dokumentacije i odnošenje, predavanje dokumentacije u razne institucije', 41);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (41, 'Administrativni radnik', true, 390 , 'Građevinskoj firmi potreban administrativni radnik.Zainteresovani kandidati mogu se javiti na telefon.', 41);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (75, 'Call centar agent - nemački jezik', false, 500, 'Potreban nam je call centar agent sa znanjem nemačkog jezika (srednji nivo) za ogranak švajcarske firme u Beogradu.', 1);
insert into oglas(idCoveka,Naslov,Tip,Plata,Opis,Mesto) values (75, 'Operateri', false, 400, 'Nemačkoj kompaniji sa sedištem u Beogradu hitno potrebni kol centar operateri. Fiksna plata. Moguć rad od kuće kao i rad na procenat.', 1);

insert into telefoni values(1, '0601234567');
insert into telefoni values(2, '0601324567');
insert into telefoni values(3, '0603214567');
insert into telefoni values(4, '0601234765');
insert into telefoni values(5, '0611234567');
insert into telefoni values(6, '0611324567');
insert into telefoni values(7, '0616950099');
insert into telefoni values(8, '0611234765');
insert into telefoni values(9, '0651234567');
insert into telefoni values(10, '065134489');
insert into telefoni values(11, '062256648');
insert into telefoni values(12, '064993618');
insert into telefoni values(13, '061114978');
insert into telefoni values(14, '0693636990');
insert into telefoni values(15, '0693214567');
insert into telefoni values(16, '0648891234');
insert into telefoni values(17, '0614455667');
insert into telefoni values(18, '0613214567');
insert into telefoni values(19, '0696365478');
insert into telefoni values(20, '0612336497');
insert into telefoni values(21, '0602255897');
insert into telefoni values(22, '0605005004');
insert into telefoni values(23, '0624478914');
insert into telefoni values(24, '0602223334');
insert into telefoni values(25, '0649788914');
insert into telefoni values(26, '0612036978');
insert into telefoni values(27, '0649987154');
insert into telefoni values(28, '0612003600');
insert into telefoni values(29, '0691455303');
insert into telefoni values(30, '0691002003');
insert into telefoni values(31, '0696003334');
insert into telefoni values(32, '0697778882');
insert into telefoni values(33, '0601840650');
insert into telefoni values(34, '0609961107');
insert into telefoni values(35, '0647171201');
insert into telefoni values(36, '0630020530');
insert into telefoni values(37, '0613412301');
insert into telefoni values(38, '0618822005');
insert into telefoni values(39, '0613214567');
insert into telefoni values(40, '0616935570');
insert into telefoni values(41, '0641789369');
insert into telefoni values(42, '0654849435');
insert into telefoni values(43, '0641444505');
insert into telefoni values(44, '0617852414');
insert into telefoni values(44, '0692225550');
insert into telefoni values(46, '0678782501');
insert into telefoni values(47, '0648250311');
insert into telefoni values(48, '0681245656');
insert into telefoni values(49, '0647891478');
insert into telefoni values(50, '0614550263');
insert into telefoni values(51, '0649963512');
insert into telefoni values(52, '0601423560');
insert into telefoni values(53, '0619334567');
insert into telefoni values(54, '0645502013');
insert into telefoni values(55, '0614141220');
insert into telefoni values(56, '0647911450');
insert into telefoni values(57, '0654565351');
insert into telefoni values(58, '0647788991');
insert into telefoni values(59, '0616565442');
insert into telefoni values(60, '0642525034');
insert into telefoni values(61, '0614477553');
insert into telefoni values(62, '0613365021');
insert into telefoni values(63, '0693737812');
insert into telefoni values(64, '0641010203');
insert into telefoni values(65, 'y0618914363');
insert into telefoni values(66, '0601496637');
insert into telefoni values(67, '0603332201');
insert into telefoni values(68, '0601414774');
insert into telefoni values(69, '0611231524');
insert into telefoni values(70, '0619901007');
insert into telefoni values(71, '0613474356');
insert into telefoni values(72, '0614141203');
insert into telefoni values(73, '0614565360');
insert into telefoni values(74, '0611147741');
insert into telefoni values(75, '0613655214');


insert into tags(tag) values ("IT");
insert into tags(tag) values ("Medicina");
insert into tags(tag) values ("Turizam");
insert into tags(tag) values ("Ugostiteljstvo");
insert into tags(tag) values ("Industrija");
insert into tags(tag) values ("Poljoprivreda");
insert into tags(tag) values ("Obrazovanje");
insert into tags(tag) values ("Administarstvo");

insert into podtags(idkategorije,podkategorija) values(1,"Java"); 
insert into podtags(idkategorije,podkategorija) values(1,"C++"); 
insert into podtags(idkategorije,podkategorija) values(1,"DataScience"); 
insert into podtags(idkategorije,podkategorija) values(1,"Python"); 
insert into podtags(idkategorije,podkategorija) values(1,"Front-End"); 
insert into podtags(idkategorije,podkategorija) values(2,"Medicinska sestra");
insert into podtags(idkategorije,podkategorija) values(2,"Negovatelj"); 
insert into podtags(idkategorije,podkategorija) values(2,"Psiholog");
insert into podtags(idkategorije,podkategorija) values(3,"Prevodilac"); 
insert into podtags(idkategorije,podkategorija) values(3,"Vodic"); 
insert into podtags(idkategorije,podkategorija) values(4,"Konobar"); 
insert into podtags(idkategorije,podkategorija) values(4,"Kuvar"); 
insert into podtags(idkategorije,podkategorija) values(5,"Proizvodnja"); 
insert into podtags(idkategorije,podkategorija) values(5,"Zavarivac"); 
insert into podtags(idkategorije,podkategorija) values(5,"Automehanicar"); 
insert into podtags(idkategorije,podkategorija) values(6,"Farmer"); 
insert into podtags(idkategorije,podkategorija) values(6,"Biolog"); 
insert into podtags(idkategorije,podkategorija) values(7,"Vaspitac"); 
insert into podtags(idkategorije,podkategorija) values(7,"Profesor"); 
insert into podtags(idkategorije,podkategorija) values(8,"Advokat"); 
insert into podtags(idkategorije,podkategorija) values(8,"Administrator");
insert into podtags(idkategorije,podkategorija) values(8,"Prodaja");

insert into tagovi values (1,1);
insert into tagovi values (2,4);
insert into tagovi values (3,5);
insert into tagovi values (4,19);
insert into tagovi values (5,19);
insert into tagovi values (6,15);
insert into tagovi values (7,20);
insert into tagovi values (8,13);
insert into tagovi values (9,6);
insert into tagovi values (10,21);
insert into tagovi values (11,1);
insert into tagovi values (12,5);
insert into tagovi values (13,3);
insert into tagovi values (14,4);
insert into tagovi values (15,2);
insert into tagovi values (16,7);
insert into tagovi values (17,6);
insert into tagovi values (18,6);
insert into tagovi values (19,21);
insert into tagovi values (20,21);
insert into tagovi values (21,21);
insert into tagovi values (22,10);
insert into tagovi values (23,10);
insert into tagovi values (24,11);
insert into tagovi values (25,12);
insert into tagovi values (26,12);
insert into tagovi values (27,11);
insert into tagovi values (28,12);
insert into tagovi values (29,22);
insert into tagovi values (30,14);
insert into tagovi values (31,13);
insert into tagovi values (32,14);
insert into tagovi values (33,16);
insert into tagovi values (34,17);
insert into tagovi values (35,16);
insert into tagovi values (36,22);
insert into tagovi values (37,18);
insert into tagovi values (38,8);
insert into tagovi values (39,19);
insert into tagovi values (40,18);
insert into tagovi values (41,8);
insert into tagovi values (42,18);
insert into tagovi values (43,22);
insert into tagovi values (44,21);

INSERT INTO lajkovi values (4,2,false);
INSERT INTO lajkovi values (4,3,true);
INSERT INTO lajkovi values (4,11,true);
INSERT INTO lajkovi values (4,13,true);
INSERT INTO lajkovi values (4,14,true);
INSERT INTO lajkovi values (4,15,true);
INSERT INTO lajkovi values (11,2,false);
INSERT INTO lajkovi values (11,11,true);
INSERT INTO lajkovi values (11,12,false);
INSERT INTO lajkovi values (11,15,true);
INSERT INTO lajkovi values (14,2,false);
INSERT INTO lajkovi values (14,3,true);
INSERT INTO lajkovi values (14,12,true);
INSERT INTO lajkovi values (14,14,true);
INSERT INTO lajkovi values (14,15,true);
INSERT INTO lajkovi values (38,9,true);
INSERT INTO lajkovi values (38,16,false);
INSERT INTO lajkovi values (38,17,true);
INSERT INTO lajkovi values (38,18,true);
INSERT INTO lajkovi values (40,9,true);
INSERT INTO lajkovi values (40,16,false);
INSERT INTO lajkovi values (40,17,true);
INSERT INTO lajkovi values (40,18,true);
INSERT INTO lajkovi values (68,9,true);
INSERT INTO lajkovi values (68,16,true);
INSERT INTO lajkovi values (68,17,false);
INSERT INTO lajkovi values (68,18,true);
INSERT INTO lajkovi values (16,19,true);
INSERT INTO lajkovi values (16,20,true);
INSERT INTO lajkovi values (16,22,true);
INSERT INTO lajkovi values (49,19,false);
INSERT INTO lajkovi values (49,20,true);
INSERT INTO lajkovi values (49,21,false);
INSERT INTO lajkovi values (49,22,false);
INSERT INTO lajkovi values (54,19,true);
INSERT INTO lajkovi values (54,20,true);
INSERT INTO lajkovi values (54,21,false);
INSERT INTO lajkovi values (7,26,true);
INSERT INTO lajkovi values (7,27,true);
INSERT INTO lajkovi values (7,28,true);
INSERT INTO lajkovi values (67,26,true);
INSERT INTO lajkovi values (67,27,true);
INSERT INTO lajkovi values (15,30,true);
INSERT INTO lajkovi values (15,31,true);
INSERT INTO lajkovi values (17,30,true);
INSERT INTO lajkovi values (17,31,true);
INSERT INTO lajkovi values (44,30,true);
INSERT INTO lajkovi values (25,33,true);
INSERT INTO lajkovi values (25,34,true);
INSERT INTO lajkovi values (58,33,false);
INSERT INTO lajkovi values (58,34,true);
INSERT INTO lajkovi values (28,37,false);
INSERT INTO lajkovi values (28,38,true);
INSERT INTO lajkovi values (28,39,true);
INSERT INTO lajkovi values (28,40,true);
INSERT INTO lajkovi values (64,37,true);
INSERT INTO lajkovi values (64,38,true);
INSERT INTO lajkovi values (64,39,true);
INSERT INTO lajkovi values (64,40,true);
INSERT INTO lajkovi values (71,37,true);
INSERT INTO lajkovi values (71,38,false);
INSERT INTO lajkovi values (71,39,true);
INSERT INTO lajkovi values (71,40,true);
INSERT INTO lajkovi values (72,37,true);
INSERT INTO lajkovi values (72,38,false);
INSERT INTO lajkovi values (72,39,true);
INSERT INTO lajkovi values (72,40,true);
INSERT INTO lajkovi values (74,37,true);
INSERT INTO lajkovi values (74,38,true);
INSERT INTO lajkovi values (74,39,true);
INSERT INTO lajkovi values (74,40,false);
INSERT INTO lajkovi values (13,21,true);
INSERT INTO lajkovi values (13,44,true);
INSERT INTO lajkovi values (13,46,false);
INSERT INTO lajkovi values (27,21,true);
INSERT INTO lajkovi values (27,44,true);
INSERT INTO lajkovi values (27,46,false);

INSERT INTO ocena values (4,2,3);
INSERT INTO ocena values (4,3,4);
INSERT INTO ocena values (4,11,4);
INSERT INTO ocena values (4,13,3);
INSERT INTO ocena values (4,14,5);
INSERT INTO ocena values (4,15,5);
INSERT INTO ocena values (11,2,4);
INSERT INTO ocena values (11,11,4);
INSERT INTO ocena values (11,12,1);
INSERT INTO ocena values (11,15,2);
INSERT INTO ocena values (14,2,2);
INSERT INTO ocena values (14,3,4);
INSERT INTO ocena values (14,12,5);
INSERT INTO ocena values (14,14,5);
INSERT INTO ocena values (14,15,5);
INSERT INTO ocena values (38,9,5);
INSERT INTO ocena values (38,16,1);
INSERT INTO ocena values (38,17,4);
INSERT INTO ocena values (38,18,4);
INSERT INTO ocena values (40,9,4);
INSERT INTO ocena values (40,16,3);
INSERT INTO ocena values (40,17,4);
INSERT INTO ocena values (40,18,4);
INSERT INTO ocena values (68,9,5);
INSERT INTO ocena values (68,16,4);
INSERT INTO ocena values (68,17,3);
INSERT INTO ocena values (68,18,4);
INSERT INTO ocena values (16,19,4);
INSERT INTO ocena values (16,20,4);
INSERT INTO ocena values (16,22,5);
INSERT INTO ocena values (49,19,3);
INSERT INTO ocena values (49,20,4);
INSERT INTO ocena values (49,21,2);
INSERT INTO ocena values (49,22,2);
INSERT INTO ocena values (54,19,5);
INSERT INTO ocena values (54,20,5);
INSERT INTO ocena values (54,21,4);
INSERT INTO ocena values (7,26,5);
INSERT INTO ocena values (7,27,4);
INSERT INTO ocena values (7,28,4);
INSERT INTO ocena values (67,26,5);
INSERT INTO ocena values (67,27,5);
INSERT INTO ocena values (15,30,3);
INSERT INTO ocena values (15,31,4);
INSERT INTO ocena values (17,30,4);
INSERT INTO ocena values (17,31,5);
INSERT INTO ocena values (44,30,5);
INSERT INTO ocena values (25,33,4);
INSERT INTO ocena values (25,34,5);
INSERT INTO ocena values (58,33,5);
INSERT INTO ocena values (58,34,3);
INSERT INTO ocena values (28,37,4);
INSERT INTO ocena values (28,38,4);
INSERT INTO ocena values (28,39,5);
INSERT INTO ocena values (28,40,4);
INSERT INTO ocena values (64,37,5);
INSERT INTO ocena values (64,38,4);
INSERT INTO ocena values (64,39,4);
INSERT INTO ocena values (64,40,5);
INSERT INTO ocena values (71,37,3);
INSERT INTO ocena values (71,38,5);
INSERT INTO ocena values (71,39,3);
INSERT INTO ocena values (71,40,4);
INSERT INTO ocena values (72,37,5);
INSERT INTO ocena values (72,38,3);
INSERT INTO ocena values (72,39,4);
INSERT INTO ocena values (72,40,3);
INSERT INTO ocena values (74,37,5);
INSERT INTO ocena values (74,38,3);
INSERT INTO ocena values (74,39,4);
INSERT INTO ocena values (74,40,2);
INSERT INTO ocena values (13,21,5);
INSERT INTO ocena values (13,44,4);
INSERT INTO ocena values (13,46,3);
INSERT INTO ocena values (27,21,4);
INSERT INTO ocena values (27,44,5);
INSERT INTO ocena values (27,46,2);